/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/configuration/JpaConfiguration.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
$output.java($Configuration, "JpaConfiguration")##

$output.require("java.util.Properties")##

$output.require("javax.sql.DataSource")##

$output.require("org.springframework.beans.factory.annotation.Value")##
$output.require("org.springframework.context.annotation.Bean")##
$output.require("org.springframework.context.annotation.Configuration")##
$output.require("org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor")##
$output.require("org.springframework.orm.jpa.JpaTransactionManager")##
$output.require("org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean")##
$output.require("org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter")##
$output.require("org.springframework.web.servlet.config.annotation.EnableWebMvc")##

@Configuration
public class $output.currentClass {

    @Value("classpath:hibernate.properties")
    private Properties jpaProperties;

    /**
     * Enable exception translation for beans annotated with @Repository
     */
    @Bean
    public PersistenceExceptionTranslationPostProcessor exceptionTranslation() {
        return new PersistenceExceptionTranslationPostProcessor();
    }

    /**
     * @see read http://www.springframework.org/docs/reference/transaction.html
     */
    @Bean
    public JpaTransactionManager transactionManager() {
        return new JpaTransactionManager();
    }

    /**
     * Build the entity manager with Hibernate as a provider.
     */
    @Bean
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {
        LocalContainerEntityManagerFactoryBean emf = new LocalContainerEntityManagerFactoryBean();
        emf.setDataSource(dataSource);
        // We set the persistenceXmlLocation to a different name to make it work on JBoss.
        emf.setPersistenceXmlLocation("classpath:META-INF/spring-persistence.xml");
        emf.setPersistenceUnitName("rahulshopPU");
        emf.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
        emf.setJpaProperties(jpaProperties);
        return emf;
    }

}
